version: '2.1'

services:
    web:
        image: chenchenchen/nginx1.14:v2
        ports:
            - "80:80"
        volumes:
            - ../cl-api:/app
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./runtime:/data/logs/
            - "phpsocket:/tmp"
        networks:
            - my-network
    php:
        image: uamyangel/alpine3.8_php72_fpm
        volumes:
            - ../cl-api:/app
#            - ./config/php-fpm.conf:/usr/local/etc/php-fpm.conf
#            - ./config/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
#            - ./config/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
#            - ./config/php.ini:/usr/local/etc/php/php.ini
            - ./config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./runtime:/data/logs/
            - "phpsocket:/tmp"
        networks:
            - my-network
networks:
    my-network:
        driver: bridge

volumes:
    phpsocket: